import eslint from "@eslint/js";

export default [
  eslint.configs.recommended,
  {
    files: ["src/**/*.js", "data/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        document: "readonly",
        window: "readonly",
        localStorage: "readonly",
        requestAnimationFrame: "readonly",
        Worker: "readonly",
        fetch: "readonly",
        self: "readonly",
        caches: "readonly",
        clients: "readonly",
        DOMParser: "readonly",
        Image: "readonly",
        HTMLElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        URL: "readonly",
        Response: "readonly",
        Request: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        Math: "readonly",
        Array: "readonly",
        Object: "readonly",
        Map: "readonly",
        Set: "readonly",
        Promise: "readonly",
        JSON: "readonly",
        Error: "readonly",
        Number: "readonly",
        String: "readonly",
        Boolean: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        DocumentFragment: "readonly",
        FileReader: "readonly",
        ResizeObserver: "readonly",
        alert: "readonly",
      },
    },
    rules: {
      semi: ["error", "always"],
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
      "prefer-const": "warn",
      "no-var": "error",
    },
  },
  {
    ignores: ["app.min.js", "app.bundle.js", "ce-match-worker.min.js", "app.js"],
  },
];
